version: "3.9"
services:
  mariadb:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "awesomeRootPassword"
      MYSQL_DATABASE: "projectsjobs"
    volumes:
      - $PWD/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    container_name: "mariadb_pj"
  node:
    build: .
    ports:
      - "3000:3000"
    container_name: "node_pj"
